function a = ACC(xl, xf, vl, vf, auxdata)
    head_way = xl - xf - auxdata.l;
    V = auxdata.v_max .* ((tanh(head_way - auxdata.safe_dist) + ...
                    tanh(auxdata.l + auxdata.safe_dist))./ ...
                    (1 + tanh(auxdata.l + auxdata.safe_dist)));
    a = auxdata.alpha *(V - vf) + ...
        auxdata.beta * (vl - vf) ./ (head_way.^2);
end 