function data = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  T3MWRFVXLW056972MASTERARRAY05373 = IMPORTFILE(FILENAME) reads data
%  from text file FILENAME for the default selection.  Returns the data
%  as a table.
%
%  T3MWRFVXLW056972MASTERARRAY05373 = IMPORTFILE(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  T3MWRFVXLW056972masterArray05373 = importfile("/Users/arwaalanqary/Dropbox (MIT)/Berkeley/git/optimal_control/2021-03-08-22-35-14_2T3MWRFVXLW056972_masterArray_0_5373.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 30-Jan-2022 12:38:27

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 21);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "index", "Time", "Velocity", "Acceleration", "SpaceGap", "LateralDistance", "RelativeVelocity", "LongitudeGPS", "LatitudeGPS", "Score", "TrackID", "L_Approach", "R_Approach", "L_Adjacent", "R_Adjacent", "DistanceGPS", "MileMarker", "Bearing", "DrivingDir", "ValidPt"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["DrivingDir", "ValidPt"], "EmptyFieldRule", "auto");

% Import the data
data = readtable(filename, opts);

end